import { useEffect, useState } from 'react'
import { AlertCircle, ArrowUpRight, Building2, CheckCircle2, FileCheck2, FilePlus2, FileText, MapPinned, RefreshCw, Search, UploadCloud } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import './App.css'
import { Badge, SeverityBadge } from './components/Badge'
import { Layout, type View } from './components/Layout'
import { api } from './services/api'
import type { DocumentRecord, DocumentType, HealthResponse, InfrastructureProject, ParcelRecord, ValidationResponse } from './types/api'

function formatArea(value: number | null | undefined) { return value == null ? '—' : `${value.toLocaleString(undefined, { maximumFractionDigits: 1 })} m²` }
function formatDate(value: string) { return new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)) }

function ErrorMessage({ message, onRetry }: { message: string; onRetry?: () => void }) { return <div className="error-state"><AlertCircle size={19} /><div><strong>Unable to load this view</strong><p>{message}</p></div>{onRetry && <button className="button button-secondary" onClick={onRetry}><RefreshCw size={15} /> Retry</button>}</div> }
function EmptyState({ icon: Icon, title, message }: { icon: LucideIcon; title: string; message: string }) { return <div className="empty-state"><div className="empty-icon"><Icon size={23} /></div><strong>{title}</strong><p>{message}</p></div> }
function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div> }

function Home({ health, documents, parcels, infrastructure, onNavigate }: { health: HealthResponse | null; documents: DocumentRecord[]; parcels: ParcelRecord[]; infrastructure: InfrastructureProject[]; onNavigate: (view: View) => void }) {
  const reviewCount = parcels.filter(parcel => parcel.verification_status !== 'VERIFIED').length
  return <><PageHeader eyebrow="Operations overview" title="Good morning, operator" description="A single view of document intake, parcel verification, and spatial review." action={<div className="date-stamp">{new Intl.DateTimeFormat('en-IN', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date())}</div>} />
    <div className="notice-banner"><div className="notice-icon"><CheckCircle2 size={19} /></div><div><strong>Backend connection {health?.status === 'ok' ? 'healthy' : 'available'}</strong><span>{health ? `Database ${health.database}. Environment: ${health.environment}.` : 'Connect the local FastAPI service to load live records.'}</span></div><span className="notice-label">LIVE DATA</span></div>
    <div className="stat-grid"><button className="stat-card" onClick={() => onNavigate('documents')}><span className="stat-icon blue"><FileCheck2 size={19} /></span><span className="stat-label">Documents in register</span><strong>{documents.length}</strong><small>Uploaded records</small><ArrowUpRight className="stat-arrow" size={16} /></button><button className="stat-card" onClick={() => onNavigate('parcels')}><span className="stat-icon green"><MapPinned size={19} /></span><span className="stat-label">Parcels in review</span><strong>{reviewCount}</strong><small>From live parcel register</small><ArrowUpRight className="stat-arrow" size={16} /></button><button className="stat-card" onClick={() => onNavigate('validation')}><span className="stat-icon amber"><ShieldIcon /></span><span className="stat-label">Verification queue</span><strong>{reviewCount}</strong><small>Human review required</small><ArrowUpRight className="stat-arrow" size={16} /></button><button className="stat-card" onClick={() => onNavigate('infrastructure')}><span className="stat-icon slate"><BuildingIcon /></span><span className="stat-label">Infrastructure corridors</span><strong>{infrastructure.length}</strong><small>Projects in register</small><ArrowUpRight className="stat-arrow" size={16} /></button></div>
    <div className="home-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">Operator queue</span><h2>Documents needing attention</h2></div><button className="text-button" onClick={() => onNavigate('documents')}>View all <ArrowUpRight size={14} /></button></div>{documents.length === 0 ? <EmptyState icon={FilePlus2} title="No documents uploaded" message="Upload a deed, khata, khasra, or survey map to begin." /> : <div className="activity-list">{documents.slice(0, 4).map(document => <div className="activity-row" key={document.id}><div className="file-type">{document.original_filename.split('.').pop()?.toUpperCase()}</div><div className="activity-copy"><strong>{document.original_filename}</strong><span>{document.parcel_id ? `Parcel ${document.parcel_id}` : 'Unassigned parcel'} · {formatDate(document.created_at)}</span></div><Badge value={document.status} /></div>)}</div>}</section><section className="panel guidance-panel"><div className="panel-heading"><div><span className="eyebrow">Workflow note</span><h2>Human verification first</h2></div><ShieldIcon /></div><p>Documents currently stop at <strong>Ready for OCR</strong>. AI extraction, OCR, and legal verification are intentionally not active in this prototype.</p><div className="workflow-line"><span className="done">1</span><span>Upload document</span><i /><span className="done">2</span><span>Associate parcel</span><i /><span className="future">3</span><span>Verify fields</span></div><button className="button button-primary" onClick={() => onNavigate('documents')}><UploadCloud size={16} /> Open document register</button></section></div>
  </>
}
function ShieldIcon() { return <FileCheck2 size={19} /> }
function BuildingIcon() { return <Building2 size={19} /> }

function Documents({ documents, parcels, onRefresh, setMessage }: { documents: DocumentRecord[]; parcels: ParcelRecord[]; onRefresh: () => void; setMessage: (message: string) => void }) {
  const [file, setFile] = useState<File | null>(null); const [parcelId, setParcelId] = useState(''); const [documentType, setDocumentType] = useState<DocumentType>('UNKNOWN'); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [selected, setSelected] = useState<string | null>(null); const [assignParcel, setAssignParcel] = useState('')
  async function upload() { if (!file) return setError('Choose a PDF, JPEG, or PNG first.'); setBusy(true); setError(''); try { await api.uploadDocument(file, parcelId, documentType); setFile(null); setParcelId(''); setMessage('Document uploaded and stored as Ready for OCR.'); onRefresh() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Upload failed.') } finally { setBusy(false) } }
  async function assign(document: DocumentRecord) { setBusy(true); setError(''); try { await api.associateDocument(document.id, assignParcel || null); setMessage(assignParcel ? 'Document associated with parcel.' : 'Document detached from parcel.'); onRefresh() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Association failed.') } finally { setBusy(false) } }
  return <><PageHeader eyebrow="Operator workspace" title="Document register" description="Upload source records, track processing state, and keep each document linked to the right parcel." action={<label className="button button-primary upload-label"><UploadCloud size={16} /> Select document<input type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" onChange={event => setFile(event.target.files?.[0] ?? null)} /></label>} />
    {error && <ErrorMessage message={error} />}{selected && <div className="toast-inline"><CheckCircle2 size={16} /> {selected}</div>}
    <section className="upload-strip"><div className="upload-drop"><UploadCloud size={21} /><div><strong>{file ? file.name : 'Add a document to the register'}</strong><span>PDF, JPEG or PNG · local authorized records only</span></div></div><div className="form-inline"><select value={documentType} onChange={event => setDocumentType(event.target.value as DocumentType)} aria-label="Document type"><option value="UNKNOWN">Document type</option><option value="LAND_DEED">Land deed</option><option value="SALE_DEED">Sale deed</option><option value="KHATA">Khata</option><option value="KHASRA">Khasra</option><option value="LAND_RECORD">Land record</option><option value="SURVEY_MAP">Survey map</option></select><select value={parcelId} onChange={event => setParcelId(event.target.value)} aria-label="Associate parcel"><option value="">No parcel association</option>{parcels.map(parcel => <option key={parcel.id} value={parcel.id}>{parcel.khasra_number} · {parcel.village}</option>)}</select><button className="button button-primary" onClick={upload} disabled={busy || !file}>{busy ? 'Uploading…' : 'Upload record'}</button></div></section>
    <section className="panel table-panel"><div className="panel-heading"><div><span className="eyebrow">Live API records</span><h2>All documents <span className="count-pill">{documents.length}</span></h2></div><button className="icon-button" onClick={onRefresh} aria-label="Refresh documents"><RefreshCw size={17} /></button></div>{documents.length === 0 ? <EmptyState icon={FileText} title="No documents in the register" message="Upload the first authorized record to begin the operator workflow." /> : <div className="table-wrap"><table><thead><tr><th>Document</th><th>Type</th><th>Parcel link</th><th>Processing status</th><th>Added</th><th /></tr></thead><tbody>{documents.map(document => <tr key={document.id}><td><div className="table-file"><div className="file-type small">{document.original_filename.split('.').pop()?.toUpperCase()}</div><div><strong>{document.original_filename}</strong><span>{Math.round(document.file_size_bytes / 1024)} KB</span></div></div></td><td>{document.document_type.replaceAll('_', ' ')}</td><td>{document.parcel_id ? <span className="mono">{document.parcel_id}</span> : <span className="muted">Unassigned</span>}</td><td><Badge value={document.status} /></td><td>{formatDate(document.created_at)}</td><td><button className="link-button" onClick={() => { setSelected(document.id); setAssignParcel(document.parcel_id ?? '') }}>{selected === document.id ? 'Editing' : 'Manage'}</button></td></tr>)}</tbody></table></div>}{selected && <div className="assignment-editor"><div><strong>Parcel association</strong><span>Reassign or detach this document from a parcel.</span></div><select value={assignParcel} onChange={event => setAssignParcel(event.target.value)}><option value="">No parcel association</option>{parcels.map(parcel => <option key={parcel.id} value={parcel.id}>{parcel.khasra_number} · {parcel.village}</option>)}</select><button className="button button-secondary" onClick={() => { const document = documents.find(item => item.id === selected); if (document) void assign(document) }} disabled={busy}>Save association</button><button className="link-button" onClick={() => setSelected(null)}>Cancel</button></div>}</section>
    <section className="future-card"><div className="future-icon"><FileCheck2 size={20} /></div><div><span className="eyebrow">Future verification layer</span><h2>Proofreading workspace</h2><p>OCR text comparison and field-level verification will appear here when the extraction service is introduced. No extracted values are fabricated in this version.</p></div><Badge value="COMING_NEXT" /></section>
  </>
}
function Parcels({ parcels, onRefresh, onSelect }: { parcels: ParcelRecord[]; onRefresh: (search?: string) => Promise<void>; onSelect: (parcel: ParcelRecord) => void }) {
  const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  async function searchParcels() { setLoading(true); setError(''); try { await onRefresh(search) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Parcel search failed.') } finally { setLoading(false) } }
  return <><PageHeader eyebrow="Tehsildar workspace" title="Parcel register" description="Search the live parcel register by Khasra, Khata, village, or parcel identifier." action={<button className="button button-secondary" onClick={() => void onRefresh()}><RefreshCw size={16} /> Refresh register</button>} />{error && <ErrorMessage message={error} />}
    <section className="filter-bar"><div className="search-field"><Search size={17} /><input value={search} onChange={event => setSearch(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') void searchParcels() }} placeholder="Search Khasra, Khata, village, or ID" /><button onClick={() => void searchParcels()}>{loading ? 'Searching…' : 'Search'}</button></div><span className="result-count">{parcels.length} records loaded</span></section>
    <section className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>Parcel / Khasra</th><th>Location</th><th>Khata</th><th>Recorded area</th><th>Record status</th><th>Verification</th><th /></tr></thead><tbody>{parcels.map(parcel => <tr key={parcel.id}><td><div><strong>{parcel.khasra_number}</strong><span className="mono">{parcel.id}</span></div></td><td>{parcel.village}<span className="sub-cell">{[parcel.tehsil, parcel.district].filter(Boolean).join(' · ')}</span></td><td>{parcel.khata_number ?? <span className="muted">Not recorded</span>}</td><td>{formatArea(parcel.recorded_area_m2)}</td><td><Badge value={parcel.status} /></td><td><Badge value={parcel.verification_status} /></td><td><button className="link-button" onClick={() => onSelect(parcel)}>Inspect</button></td></tr>)}</tbody></table></div>{parcels.length === 0 && <EmptyState icon={MapPinned} title="No parcels found" message="Try a broader search, or confirm the backend has parcels loaded." />}</section>
  </>
}

function Validation({ selectedParcel, validation, onRun, loading, error, onSelectParcel }: { selectedParcel: ParcelRecord | null; validation: ValidationResponse | null; onRun: () => void; loading: boolean; error: string; onSelectParcel: () => void }) {
  return <><PageHeader eyebrow="Tehsildar workspace" title="GIS validation" description="Run deterministic geometry, area, and overlap checks against the authoritative parcel API." action={<button className="button button-primary" onClick={onRun} disabled={!selectedParcel || loading}>{loading ? 'Running checks…' : 'Run validation'}</button>} />{error && <ErrorMessage message={error} />}
    {!selectedParcel ? <section className="selection-empty"><div className="empty-icon"><MapPinned size={24} /></div><h2>Select a parcel to begin</h2><p>Choose a parcel from the register to view its geometry validity, area comparison, and overlap findings.</p><button className="button button-secondary" onClick={onSelectParcel}>Open parcel register</button></section> : <><div className="selected-record"><div className="record-symbol"><MapPinned size={19} /></div><div><span className="eyebrow">Selected parcel</span><strong>{selectedParcel.khasra_number} · {selectedParcel.village}</strong><span>{selectedParcel.id} · {selectedParcel.district}, {selectedParcel.state}</span></div><Badge value={selectedParcel.verification_status} /></div>{validation ? <><div className="validation-summary"><div><span className="eyebrow">Overall review status</span><h2>{validation.summary}</h2><p>Results returned by the FastAPI validation service. The frontend does not recalculate GIS values.</p></div><SeverityBadge value={validation.overall_severity} /></div><div className="validation-metrics"><Metric label="Geometry validity" value={validation.geometry_valid ? 'Valid' : 'Invalid'} tone={validation.geometry_valid ? 'success' : 'danger'} /><Metric label="Calculated area" value={formatArea(validation.calculated_area_m2)} /><Metric label="Area difference" value={validation.area_difference_percent == null ? '—' : `${validation.area_difference_percent.toFixed(1)}%`} tone={validation.area_difference_percent && validation.area_difference_percent > 10 ? 'warning' : 'default'} /><Metric label="Boundary overlap" value={validation.overlap_detected ? `${validation.overlapping_parcel_ids.length} parcel(s)` : 'None detected'} tone={validation.overlap_detected ? 'warning' : 'success'} /></div><section className="panel findings-panel"><div className="panel-heading"><div><span className="eyebrow">Deterministic findings</span><h2>Validation findings</h2></div><span className="muted">{validation.findings.length} checks</span></div><div className="finding-list">{validation.findings.map(finding => <div className="finding-row" key={finding.code}><SeverityBadge value={finding.severity} /><div><strong>{finding.code.replaceAll('_', ' ')}</strong><p>{finding.message}</p></div>{finding.intersection_percentage != null && <span className="finding-value">{finding.intersection_percentage.toFixed(1)}% impact</span>}</div>)}</div>{validation.overlap_results.length > 0 && <div className="overlap-note"><strong>Overlapping parcel records</strong>{validation.overlap_results.map(overlap => <span key={overlap.parcel_id}>{overlap.parcel_id} · {overlap.overlap_percentage.toFixed(1)}% overlap</span>)}</div>}</section></> : <section className="selection-empty compact"><ShieldIcon /><h2>Ready to validate</h2><p>Run the backend GIS validation checks for this parcel.</p></section>}</>}
  </>
}
function Metric({ label, value, tone = 'default' }: { label: string; value: string; tone?: string }) { return <div className="metric"><span>{label}</span><strong className={`metric-${tone}`}>{value}</strong></div> }

function Infrastructure({ projects, loading, error, onRefresh }: { projects: InfrastructureProject[]; loading: boolean; error: string; onRefresh: () => void }) {
  return <><PageHeader eyebrow="Director workspace" title="Infrastructure risk" description="Review infrastructure corridors from the live project register and prepare for future risk intelligence." action={<button className="button button-secondary" onClick={onRefresh}><RefreshCw size={16} /> Refresh projects</button>} />{error && <ErrorMessage message={error} />}
    <section className="future-hero"><div className="future-hero-copy"><span className="eyebrow">Risk intelligence — coming next</span><h2>Explainable risk will follow verified spatial evidence.</h2><p>Predictive scoring is not implemented in the backend. This view intentionally shows no fabricated risk scores or model outputs. Use GIS Validation for current deterministic findings.</p><div className="future-points"><span><CheckCircle2 size={15} /> Infrastructure register connected</span><span><CheckCircle2 size={15} /> Corridor geometry available</span><span><span className="pending-dot" /> Predictive risk model pending</span></div></div><div className="future-orbit"><div className="orbit-center"><ShieldIcon /><span>RISK</span></div><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /></div></section>
    <section className="panel table-panel"><div className="panel-heading"><div><span className="eyebrow">Live API records</span><h2>Infrastructure corridors <span className="count-pill">{projects.length}</span></h2></div>{loading && <span className="muted">Loading…</span>}</div>{projects.length === 0 ? <EmptyState icon={Building2} title="No infrastructure projects" message="Projects will appear here when they are loaded into the backend register." /> : <div className="table-wrap"><table><thead><tr><th>Project</th><th>Type</th><th>Status</th><th>CRS</th><th>Risk intelligence</th></tr></thead><tbody>{projects.map(project => <tr key={project.id}><td><strong>{project.name}</strong><span className="mono">{project.id}</span></td><td>{project.project_type.replaceAll('_', ' ')}</td><td><Badge value={project.status} /></td><td>EPSG:{project.srid}</td><td><Badge value="COMING_NEXT" /></td></tr>)}</tbody></table></div>}</section>
  </>
}

function App() {
  const [view, setView] = useState<View>('home'); const [documents, setDocuments] = useState<DocumentRecord[]>([]); const [parcels, setParcels] = useState<ParcelRecord[]>([]); const [infrastructure, setInfrastructure] = useState<InfrastructureProject[]>([]); const [health, setHealth] = useState<HealthResponse | null>(null); const [selectedParcel, setSelectedParcel] = useState<ParcelRecord | null>(null); const [validation, setValidation] = useState<ValidationResponse | null>(null); const [validationError, setValidationError] = useState(''); const [validationLoading, setValidationLoading] = useState(false); const [globalError, setGlobalError] = useState(''); const [message, setMessage] = useState('')
  async function loadDocuments() { try { setDocuments(await api.listDocuments()); setGlobalError('') } catch (reason) { setGlobalError(reason instanceof Error ? reason.message : 'Documents unavailable.') } }
  async function loadParcels(search = '') { const result = await api.listParcels(search); setParcels(result.items); if (selectedParcel) setSelectedParcel(result.items.find(parcel => parcel.id === selectedParcel.id) ?? selectedParcel) }
  async function loadInfrastructure() { try { setInfrastructure(await api.listInfrastructure()) } catch (reason) { setGlobalError(reason instanceof Error ? reason.message : 'Infrastructure unavailable.') } }
  useEffect(() => {
    const timer = window.setTimeout(() => { void Promise.all([api.getHealth().then(setHealth).catch(() => setHealth(null)), loadDocuments(), loadParcels(), loadInfrastructure()]) }, 0)
    return () => window.clearTimeout(timer)
    // Initial data loading intentionally runs once for the mounted dashboard.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
  async function runValidation() { if (!selectedParcel) return; setValidationLoading(true); setValidationError(''); try { setValidation(await api.validateParcel(selectedParcel.id)) } catch (reason) { setValidationError(reason instanceof Error ? reason.message : 'Validation failed.') } finally { setValidationLoading(false) } }
  function navigate(nextView: View) { setView(nextView); setMessage('') }
  return <Layout view={view} onNavigate={navigate}>{message && <div className="global-toast"><CheckCircle2 size={16} /> {message}<button onClick={() => setMessage('')} aria-label="Dismiss message">×</button></div>}{globalError && <ErrorMessage message={globalError} onRetry={() => { void loadDocuments(); void loadParcels(); void loadInfrastructure() }} />}{view === 'home' && <Home health={health} documents={documents} parcels={parcels} infrastructure={infrastructure} onNavigate={navigate} />}{view === 'documents' && <Documents documents={documents} parcels={parcels} onRefresh={() => void loadDocuments()} setMessage={setMessage} />}{view === 'parcels' && <Parcels parcels={parcels} onRefresh={() => loadParcels()} onSelect={parcel => { setSelectedParcel(parcel); setValidation(null); setView('validation') }} />}{view === 'validation' && <Validation selectedParcel={selectedParcel} validation={validation} onRun={() => void runValidation()} loading={validationLoading} error={validationError} onSelectParcel={() => setView('parcels')} />}{view === 'infrastructure' && <Infrastructure projects={infrastructure} loading={false} error={globalError} onRefresh={() => void loadInfrastructure()} />}</Layout>
}

export default App